### ISSUE TITLE
Rajouter la définition de la table

### ISSUE THREAD

**Issue by LucasLecot** [Bunkermaster/Web1KandT#1]
-- phpMyAdmin SQL Dump
-- version 4.4.10
-- http://www.phpmyadmin.net
--
-- Client :  localhost:8889
-- Généré le :  Mar 28 Février 2017 à 11:51
-- Version du serveur :  5.5.42
-- Version de PHP :  7.0.8

SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
SET time_zone = "+00:00";

--
-- Base de données :  `kandt`
--

-- --------------------------------------------------------

--
-- Structure de la table `onglets`
--

CREATE TABLE `onglets` (
  `id` int(11) NOT NULL,
  `slug` varchar(100) COLLATE utf8mb4_unicode_ci NOT NULL,
  `nav_title` varchar(50) COLLATE utf8mb4_unicode_ci NOT NULL,
  `H1` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL,
  `paragraphe` text COLLATE utf8mb4_unicode_ci NOT NULL,
  `img` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL,
  `alt` varchar(100) COLLATE utf8mb4_unicode_ci NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

--
-- Index pour les tables exportées
--

--
-- Index pour la table `onglets`
--
ALTER TABLE `onglets`
  ADD PRIMARY KEY (`id`),
  ADD UNIQUE KEY `nav_title` (`nav_title`);

--
-- AUTO_INCREMENT pour les tables exportées
--

--
-- AUTO_INCREMENT pour la table `onglets`
--
ALTER TABLE `onglets`
  MODIFY `id` int(11) NOT NULL AUTO_INCREMENT;

**Comment by Bunkermaster** [comment]
👍
